### ISSUE TITLE
Please provide a sample using Blazor Server.

### ISSUE THREAD

**Issue by KevinLandgrave** [yushulx/blazor-barcode-sample#1]
If it's not too much trouble, could you provide an example using Blazor server?  I've seen Blazor server samples for accessing the cameraq through the browser, but don't know the difference in setup required.  

Also,  can you provide a sample that does not require reading from a file, but scans the camera image for a barcode and immediately returns the barcode text?

**Comment by xulihang** [comment]
Blazor server is much the same for this project. Scan from cameras is added.
