### ISSUE TITLE
Not working using Ipad browser

### ISSUE THREAD

**Issue by cbrownmobile** [yushulx/blazor-barcode-sample#3]
after building the Blazor project and publishing to IIS , Connecting to published site and accessing from Android phone browser, prompts for camera,  video or  file, works perfect and decodes barcode

from iPad or iPhone using Safari browser ,  never prompts for camera. I installed Edge browser on IPad and tried, still does not work.

**Comment by yushulx** [comment]
Probably it's Safari's issue. It can work in iOS Chrome.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/2202306/106418549-90f5de80-6491-11eb-9b85-41b10234001e.png)

**Comment by cbrownmobile** [comment]
Thank you

 

Clark Brown

 <mailto:cbrownmobile@gmail.com> cbrownmobile@gmail.com

Mobile | (901) 335-2596
