### ISSUE TITLE
Live scan not live scanning?

### ISSUE THREAD

**Issue by StevieTimes** [yushulx/blazor-barcode-sample#6]
I published this to azure, modifying nothing except putting in my product key as per the instructions.  When I click "Live Scan", my camera pops up on my phone (OnePlus 8T); but it is not live scanning.  After I click the camera shutter (like I'm taking a picture) of a bar code, it scans; but I'd like to "live scan".  Does live scan work for anyone?

thanks!

**Comment by xulihang** [comment]
Camera access requires HTTPS. If you are using HTTP, it will behave like this.
